<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * categoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriesRepository extends EntityRepository
{
    public function findAllOrderedByName(){
      return $this->getEntityManager()
            ->createQuery("SELECT c FROM AppBundle:Categories c ORDER BY c.name ")
          ->getResult();
    }
}
